---

- include_tasks: ../functions/get_secret.yml
  with_items:
  - { path: "{{ basedir }}/wlan_pass", type: prompt }

- name: "create folder struct for {{ servicename }}"
  file: 
    path: "{{ item }}"
    state: "directory"
  with_items:
    - "{{ basedir }}/"
    - "{{ basedir }}/config/"

- name: "create config files for {{ servicename }}"
  template: 
    src: "{{ item }}" 
    dest: "{{ basedir }}/{{ item }}"
  with_items: 
    - docker-compose.yml
    - compile.sh
    - config/badezimmer.yaml
    - config/epaper_display_01.yaml
    - config/flur.yaml
    - config/test-esp32.yaml
    - config/test-esp8266.yaml
    - config/kueche.yaml
    - config/schlafzimmer.yaml
    - config/schreibtisch.yaml
    - config/wohnzimmer.yaml
    - config/technikraum.yaml
  register: config_files

- name: download config includes files 
  get_url:
    url: "https://raw.githubusercontent.com/esphome/esphome-docs/current/_static/{{ item }}" 
    dest: "{{ basedir }}/config/{{ item }}"
  with_items:
    - webserver-v1.min.css
    - webserver-v1.min.js

- name: "stop {{ servicename }} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: absent
  when: config_files.changed 

- name: "start {{ servicename }} docker"
  community.docker.docker_compose_v2:
    project_src: "{{ basedir }}"
    state: present