---
- name: install apt-transport-https packages before adding sources
  ansible.builtin.apt:
    update_cache: false
    state: present
    name:
      - aptitude
      - debian-archive-keyring
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg

- name: get_docker repository keys
  ansible.builtin.shell: "curl -fsSL {{ item.url }} | gpg --dearmor --yes -o {{ item.file }}"
  with_items: "{{ debian_keys }}"
  when: debian_keys is defined and debian_keys|length > 0

- name: set debian repos
  ansible.builtin.template:
    src: sources.list.j2
    dest: /etc/apt/sources.list

- name: update debian repos
  ansible.builtin.apt:
    update_cache: true
