---
# Pakete installieren
- name: pakete installieren
  ansible.builtin.apt:
    update_cache: true
    state: present
    name:
      - cron-apt
      - needrestart

# Cron-Apt runs with default configuration
# Daily update at 4am

- name: add upgrade step
  ansible.builtin.template:
    src: 5-upgrade
    dest: /etc/cron-apt/action.d/5-upgrade
