

services:

  db:

    image: mariadb:12
    restart: always
    volumes:
      - "{{ basedir }}/db/:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "{{ mysql_admin_pass }}"
      MYSQL_PASSWORD: "{{ mysql_user_pass }}"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
    networks:
        - default
  
  app:

    image: wordpress:apache
    restart: always
    depends_on: 
      - db
    volumes:
      - "{{ basedir }}/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini"
      - "{{ basedir }}/data:/var/www/html"
    environment:
      WORDPRESS_DB_HOST: "db"
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD: "{{ mysql_user_pass }}"
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ servicename }}.rule=Host(`{{ domain }}`)
      - traefik.http.routers.{{ servicename }}.entrypoints=websecure
      - traefik.http.services.{{ servicename }}.loadbalancer.server.port=80      
    networks:
      - default
      - web

networks:
  web:
    external: true
