
esphome:
  name: "{{ devicename }}"

# WiFi settings 
wifi:
  ssid: "VOID-IoT"
  password: "{{ wlan_pass }}"
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPHome-{{ devicename }}"
    
# WLAN selection in fallback mode
captive_portal:
  
# Enable OTA
ota:
  - platform: esphome
    on_begin:
      then:
        - logger.log: "OTA start"
    on_progress:
      then:
        - logger.log:
            format: "OTA progress %0.1f%%"
            args: ["x"]
    on_end:
      then:
        - logger.log: "OTA end"
    on_error:
      then:
        - logger.log:
            format: "OTA update error %d"
            args: ["x"]

# Enable API (for Homeassistant)
api:

# Activates prometheus /metrics endpoint
prometheus:

# Enable logging
logger:
  level: DEBUG 
  
# Enable integrated WebServer 
web_server:
  port: 80
  css_include: "webserver-v1.min.css"
  css_url: ""
  js_include: "webserver-v1.min.js"
  js_url: ""
  
# MQTT config 
mqtt:
  broker: {{mqtt.ip}}
  discovery: true 
  discovery_unique_id_generator: mac
  discovery_object_id_generator: device_name 
  topic_prefix: "ESPHome/{{ devicename }}"
