

services:

  redis:

    image: redis:7-alpine
    restart: always
    networks:
      - default


  mysql:

    image: mariadb:12
    restart: always
    volumes:
      - "{{ basedir }}/db/:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "{{ mysql_admin_pass }}"
      MYSQL_PASSWORD: "{{ mysql_user_pass }}"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
      MARIADB_AUTO_UPGRADE: "1"
    networks:
      - default
  

  app:

    image: nextcloud:stable-apache
    restart: always
    depends_on:
      - mysql
      - redis
    volumes:
      - "{{ basedir }}/data/:/var/www/html/"
      - "{{ basedir }}/tmp/:/tmp/nextcloudtemp/"
      - "/srv/paperless/media/documents/archive/:/paperless-archive/:ro,z"
      - "/srv/paperless/consume/:/paperless-consume/:ro,z"
    environment:
      REDIS_HOST: "redis"
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
      MYSQL_PASSWORD: "{{ mysql_user_pass }}"
      MYSQL_HOST: "mysql"
      NEXTCLOUD_ADMIN_USER: "admin"
      NEXTCLOUD_ADMIN_PASSWORD: "{{nextcloud_admin_pass}}"
      NEXTCLOUD_INIT_HTACCESS: "true"
      NEXTCLOUD_UPDATE: "1"
      PHP_MEMORY_LIMIT: "2048M"
      PHP_UPLOAD_LIMIT: "512M"
      SMTP_HOST: "{{ smtp.host }}"
      SMTP_SECURE: "{{ smtp.authtype }}"
      SMTP_PORT: "{{ smtp.port }}"
      SMTP_AUTHTYPE: "{{ smtp.authtype }}"
      SMTP_NAME: "{{ smtp.username }}"
      SMTP_PASSWORD: "{{ smtp_user_pass }}"
      MAIL_FROM_ADDRESS: "{{ smtp.username }}"
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ servicename }}.rule=Host(`{{ domain }}`)
      - traefik.http.routers.{{ servicename }}.entrypoints=websecure
      - traefik.http.services.{{ servicename }}.loadbalancer.server.port=80
      - traefik.http.routers.{{ servicename }}.middlewares={{ servicename }}-headers,{{ servicename }}-dav
      - traefik.http.middlewares.{{ servicename }}-headers.headers.customrequestheaders.X-Forwarded-Proto=https
      - traefik.http.middlewares.{{ servicename }}-dav.redirectregex.permanent=true
      - traefik.http.middlewares.{{ servicename }}-dav.redirectregex.regex=https://(.*)/.well-known/(?:card|cal)dav
      - traefik.http.middlewares.{{ servicename }}-dav.redirectregex.replacement=https://$${1}/remote.php/dav
    networks:
      - default
      - web


  webcron:
    
    image: jsonfry/curl-cron:latest 
    restart: always
    depends_on:
      - app
    environment:
      OPTIONS: "--silent http://app/cron.php"
      CRON_SCHEDULE: "*/5 * * * *"
    networks:
      - default


networks:
  web:
    external: true
    
