---
- name: stop snmpd
  ansible.builtin.service: name=snmpd state=stopped

# Pakete installieren
- name: pakete installieren
  ansible.builtin.apt:
    pkg: "{{ item }}"
    update_cache: true
    state: absent
    purge: true
  with_items:
    - snmpd

- name: delete config file
  ansible.builtin.file:
    path: "/etc/snmp/snmpd.conf"
    state: absent
